### ISSUE TITLE
Unable to open your jar file

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-W13-1/main#256]
I tried double clicking your jar file (in an empty folder) and some extra files were generated but the app did not start. Also I don't have a stack trace because I can't run it through command line and the log file was empty. On Windows 10.

**Comment by akhilvuputuri** [comment]
@yjskrs hi there, thanks for testing out our application! Sorry to hear that you were unable to open the application by double-clicking but I think the explicit instructions on the course website were to open using java -jar on the command line. Did it work though when launching it using java -jar? Hope you were able to test the application in the end!
