### ISSUE TITLE
[SELFTEST - DIET] Mode (GAIN, MAINTAIN, LOSS) does not tally with the USAGE portion.

### ISSUE THREAD

**Issue by ailanthustng** [AY1920S2-CS2103T-W13-1/main#320]
![Screenshot 2020-04-10 at 14 14 34](https://user-images.githubusercontent.com/51152441/78967687-c2ce3b00-7b35-11ea-8d17-2f29ff6cc106.png)

**Comment by ailanthustng** [comment]
Suggestion: change to:

`USAGE: mode [-g] [-m] [-l]`

**Comment by Jarrod-Bob** [comment]
I have adopted Sheexiong's recommendation to use [-l, -m, -g] instead so that it does not seem like we can put all 3 together like `mode -l -m -g`
