### ISSUE TITLE
[SELFTEST - DIET] Mode (GAIN, MAINTAIN, LOSS) UG show unclear format.

### ISSUE THREAD

**Issue by sheexiong** [AY1920S2-CS2103T-W13-1/main#321]
In UG, the square bracket indicates the optional variable. In the format given below allow the user to key in `mode -m -l` at the same time.

Format: mode [-m] [-l] [-g]

Maybe can change it to [-m,-l, -g].

**Comment by Jarrod-Bob** [comment]
Fixed in upcoming PR
