### ISSUE TITLE
[SELFTEST - DIET] Error in formatting for Height and Weight example

### ISSUE THREAD

**Issue by ailanthustng** [AY1920S2-CS2103T-W13-1/main#323]
![Screenshot 2020-04-10 at 14 19 06](https://user-images.githubusercontent.com/51152441/78968051-5d2e7e80-7b36-11ea-8fc8-e7a1cc200b9f.png)

There should be a space between `height` and `170`

**Comment by ailanthustng** [comment]
![Screenshot 2020-04-10 at 14 21 36](https://user-images.githubusercontent.com/51152441/78968246-9f57c000-7b36-11ea-9196-fc2b4d46e141.png)

Same for weight.

**Comment by Jarrod-Bob** [comment]
Fixed in PR "Fixed Diet Tracker Bugs 1"
