### ISSUE TITLE
[SELFTEST - DIET] Adding item with same name and same calories returns me "This food already exists in the food book"

### ISSUE THREAD

**Issue by ailanthustng** [AY1920S2-CS2103T-W13-1/main#332]
![Screenshot 2020-04-10 at 14 31 41](https://user-images.githubusercontent.com/51152441/78968943-5dc81480-7b38-11ea-83ed-4f7d4498a12a.png)

**Comment by Jarrod-Bob** [comment]
Fixed in upcoming PR "Fixed Diet Tracker Bugs 2"
