### ISSUE TITLE
[SELFTEST - DIET] "Tracker" and "Diet Tracker" not consistent in Help command, same for EYLAH and Eylah.

### ISSUE THREAD

**Issue by ailanthustng** [AY1920S2-CS2103T-W13-1/main#334]
![Screenshot 2020-04-10 at 14 43 05](https://user-images.githubusercontent.com/51152441/78969506-acc27980-7b39-11ea-8f95-f73ecf97f094.png)

Under point `5. mode` its "Diet Tracker", but under point `6. height` and `7. weight`  its "Tracker"

**Comment by ailanthustng** [comment]
![Screenshot 2020-04-10 at 14 43 11](https://user-images.githubusercontent.com/51152441/78969589-db405480-7b39-11ea-8490-fb0d1ead213d.png)

for point `9. back` its EYLAH, but the message under that is Eylah.

**Comment by Jarrod-Bob** [comment]
Fixed in upcoming PR "Fixed Diet Tracker Bugs 1"
